import type { Metadata } from 'next';

import './globals.css';
import Navbar from '@/components/reusable/Navbar';
import Footer from '@/components/reusable/Footer';
import { geistMono, geistSans } from '@/lib/font';

export const metadata: Metadata = {
	title: 'Ran online | Elitegrounds',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
			>
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
