export const serverInfoData = [
	{ infoName: '230 Max Level | 207 Max Skill' },
	{ infoName: 'Sync Gameplay' },
	{ infoName: '6 Balanced Classes (Classic Extreme)' },
	{ infoName: 'InGame Item Mall ' },
	{ infoName: 'In-Game Registration' },
	{ infoName: 'Max Upgrade: +10' },
	{ infoName: 'Experience Rate: High' },
	{ infoName: 'Drop Rate: Low' },
	{ infoName: 'No Reform' },
	{ infoName: 'No Premium Refines' },
	{ infoName: 'No Spoon Feed' },
	{ infoName: 'Pots Based Gameplay' },
	{ infoName: 'Hunt Based' },
	{ infoName: 'Dungeon RCB1' },
	{ infoName: 'Open skills click to learn' },
	{ infoName: 'Pull/Push (No anti skills, stuns and etc)' },
	{ infoName: 'Official Gunner Int Summon' },
	{ infoName: 'Official use of Contribution & Activity Points' },
	{ infoName: 'Official Item Combination' },
	{ infoName: 'Official Item and System Update' },
	{ infoName: 'Last weapon: Black Dragon & Astral Weapon(TBA)' },
	{ infoName: 'Last Armor: Celestial Set And Dark Lunar(TBA)' },
	{ infoName: 'PVP Events' },
	{ infoName: 'Official Tyranny War (GvG)' },
	{ infoName: 'Official School War' },
	{ infoName: 'Official Club War' },
	{ infoName: '101% Free to play' },
	{ infoName: 'Guaranteed 101% Play to earn' }
];
